name: CI

on:
  pull_request:
    branches: ['**']

jobs:
  lint-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x # LTS버전인 22버전으로 실행

      - name: Install dependencies
        run: npm ci

      - name: Run lint
        run: npm run lint

      - name: Build React app
        run: npm run build
